# Data Trends in Allegheny County's Fatal Accidental Overdoses, 2007-Present

The code below reads in a csv file with data on fatal accidental drug overdoses that have occurred in Allegheny County since 2007, then parses the data so that the fatalities can be sorted by age, race, sex, location (zip code), and incident year. 
<br>

The data is available through the [Western PA Regional Data Center](https://data.wprdc.org/dataset/allegheny-county-fatal-accidental-overdoses). 

**Research questions:**<br>
1) Which year in the dataset had the highest number of fatal accidental overdoses? <br>
2) When was the greatest fluctuation in fatality rates from one year to the next?

In [19]:
# I used the same structure from Eric's Tri Water demo during our Week 3 class for the function below

from csv import DictReader

def sort_data_dict():
    """creates a dictionary to store pertinent data from the original dataset, reads in the csv of the original dataset,
    and loops through the data to organize it into the new dictionary"""
    # Create data tracking container prior to iterating over csv
    # empty dicts as values for keys will be added to as we iterate
    od_summary = {'incident_count':0, 'year':{}, 'sex':{}, 'race':{}, 'age':{}, 'location':{}}
    # use with open to read in file object
    with open('WPRDC_fatal_overdose.csv') as overdose_file:
        # pass file object to DictReader, creating an iterable reader object
        d_reader = DictReader(overdose_file)
        # loop over each row to display contents
        for record in d_reader:
            # tabulate records as we go
            od_summary['incident_count'] = od_summary['incident_count'] + 1
            #print('Running record count: ', od_summary['incident_count'])
            # check location dict for presence of our current records' zip code
            if record['incident_zip'] not in od_summary['location']:
                # we need to add the zip to our dict with count 1
                od_summary['location'][record['incident_zip']] = 1
            else:
                # when triggered, our zip is already in our location dict
                od_summary['location'][record['incident_zip']] += 1
            if record['case_year'] not in od_summary['year']:
                od_summary['year'][record['case_year']] = 1
            else:
                od_summary['year'][record['case_year']] += 1
            if record['age'] not in od_summary['age']:
                od_summary['age'][record['age']] = 1
            else:
                od_summary['age'][record['age']] += 1
            if record['sex'] not in od_summary['sex']:
                od_summary['sex'][record['sex']] = 1
            else: 
                od_summary['sex'][record['sex']] += 1
            if record['race'] not in od_summary['race']:
                od_summary['race'][record['race']] = 1
            else:
                od_summary['race'][record['race']] += 1
        return od_summary

In [20]:
# The function below displays counts of each occurence of each category for any dictionary key in od_summary

def view_agg_data(dict_key):
    """displays total number of records for each value in a given dictionary key"""
    od_summary = sort_data_dict()
    for value in sorted(od_summary[dict_key]):
        print(value, ': ', od_summary[dict_key][value])

view_agg_data('year')

2007 :  27353
2008 :  28276
2009 :  26793
2010 :  27451
2011 :  31689
2012 :  34969
2013 :  32875
2014 :  37419
2015 :  51581
2016 :  78983
2017 :  90271
2018 :  52623
2019 :  60355
2020 :  49986
2021 :  25

In [21]:
# calling the view_agg_data function again to view breakdown by race...
view_agg_data('race')

 :  559
A :  1205
B :  95903
H :  2807
I :  243
M :  490
O :  1396
U :  244
W :  527802

In [22]:
# and again to view data by sex...
view_agg_data('sex')

 :  244
F :  195783
M :  434622

In [23]:
# and again to view data by age...
view_agg_data('age')

 :  244
0 :  122
1 :  611
12 :  122
15 :  247
16 :  733
17 :  1099
18 :  1897
19 :  4280
20 :  5603
21 :  6342
22 :  6740
23 :  9122
24 :  10659
25 :  12751
26 :  13642
27 :  15136
28 :  17041
29 :  18042
30 :  18192
31 :  16346
32 :  16980
33 :  14960
34 :  18187
35 :  14838
36 :  17005
37 :  17089
38 :  15985
39 :  17103
40 :  13922
41 :  14252
42 :  12827
43 :  13125
44 :  13850
45 :  15655
46 :  16797
47 :  16110
48 :  13899
49 :  16692
50 :  15067
51 :  19752
52 :  18305
53 :  14181
54 :  14800
55 :  13080
56 :  13675
57 :  12141
58 :  13575
59 :  11075
60 :  9110
61 :  6798
62 :  5267
63 :  6352
64 :  3792
65 :  4152
66 :  2448
67 :  1584
68 :  1955
69 :  1103
70 :  488
71 :  461
72 :  122
73 :  735
74 :  551
75 :  489
76 :  245
78 :  123
79 :  122
83 :  122
84 :  244
85 :  122
88 :  244
91 :  122

In [13]:
# And once more to view data by zipcode. There are a LOT of null and invalid entries in zipcodes. 
view_agg_data('location')

 :  61855
10002 :  610
1201 :  605
1220 :  615
12501 :  240
13219 :  610
14218 :  610
14607 :  605
14769 :  610
15-71 :  615
15001 :  3670
15003 :  6110
15005 :  2440
15007 :  1230
15009 :  605
15010 :  2450
15012 :  1230
15014 :  8590
15015 :  1830
15016 :  610
15017 :  22020
15018 :  1230
15020 :  1820
15021 :  615
15022 :  1840
15024 :  14725
15025 :  40060
15026 :  2440
15027 :  610
15030 :  2435
15031 :  1830
15033 :  1835
15034 :  6860
15035 :  6140
15037 :  20900
15038 :  1220
15041 :  610
15042 :  1830
15044 :  26840
15045 :  21780
15046 :  5520
15047 :  610
15049 :  2450
15051 :  2445
15052 :  615
15056 :  1215
15057 :  11605
15058 :  610
15061 :  1520
15063 :  1830
15064 :  2440
15065 :  26165
15066 :  2440
15068 :  25790
15071 :  11485
15074 :  3650
15076 :  3060
15081 :  610
15083 :  605
15084 :  30925
15085 :  5490
15086 :  615
15088 :  1725
15089 :  1225
15090 :  21850
15101 :  22630
15102 :  31150
15104 :  33375
15106 :  59765
15107 :  615
15108 :  59055
15110 :  20520
15112 :  7920
15116 :  17640
15120 :  66180
15122 :  43740
15124 :  610
15126 :  12230
15129 :  11685
15131 :  11625
15132 :  87180
15133 :  8725
15135 :  6700
15136 :  96090
15137 :  26410
15139 :  12220
15140 :  19030
15142 :  3055
15143 :  15705
15144 :  9765
15145 :  21975
15146 :  40945
15147 :  43080
15148 :  12195
15162 :  620
15201 :  46460
15202 :  64555
15203 :  42070
15204 :  34030
15205 :  61320
15206 :  70580
15207 :  44450
15208 :  28360
15209 :  40765
15210 :  157125
15211 :  57145
15212 :  124845
15213 :  23815
15214 :  36945
15215 :  34295
15216 :  85190
15217 :  23190
15218 :  27010
15219 :  55805
15220 :  32400
15221 :  76475
15222 :  19390
15223 :  32915
15224 :  35930
15225 :  8540
15226 :  58780
15227 :  79390
15228 :  18700
15229 :  28820
15232 :  6125
15233 :  6695
15234 :  31750
15235 :  81980
15236 :  55235
15237 :  42715
15238 :  15115
15239 :  28140
15241 :  15280
15243 :  7950
15260 :  605
15275 :  610
15301 :  6635
1531 :  610
15315 :  615
15317 :  3720
15321 :  1220
15330 :  615
15332 :  6115
15336 :  605
15340 :  610
15342 :  610
15344 :  1220
15360 :  610
15365 :  610
15367 :  1835
15401 :  1830
15413 :  610
15425 :  1220
15431 :  615
15436 :  615
15458 :  610
15475 :  610
15478 :  615
15554 :  610
15601 :  2440
15607 :  605
15611 :  615
15612 :  610
15613 :  3675
15618 :  1220
15626 :  1220
15627 :  610
15628 :  400
15632 :  1830
15633 :  610
15636 :  605
15639 :  615
15642 :  7395
15644 :  1220
15650 :  1220
15656 :  3050
15666 :  1840
15668 :  3050
15670 :  615
15690 :  3670
15697 :  615
15701 :  1840
15717 :  610
15765 :  610
15767 :  615
15920 :  610
15924 :  605
15944 :  1220
16001 :  3050
16002 :  610
16023 :  610
16028 :  1230
16037 :  610
16046 :  1825
16055 :  1830
16057 :  610
16059 :  1220
16061 :  610
16066 :  3670
16101 :  1845
16117 :  1225
16134 :  1220
16137 :  610
16146 :  1220
16160 :  610
16201 :  1220
16210 :  610
16218 :  375
16226 :  610
16228 :  610
16229 :  615
16230 :  605
16239 :  615
16242 :  610
16254 :  610
16255 :  615
16301 :  610
16316 :  620
16323 :  1215
16335 :  615
16341 :  610
16350 :  605
16362 :  615
16373 :  610
16403 :  610
16407 :  615
16501 :  610
16503 :  610
16508 :  605
16601 :  610
16627 :  610
16648 :  615
16875 :  610
17011 :  620
17043 :  615
17057 :  610
17070 :  620
17202 :  605
17260 :  615
17401 :  610
17569 :  610
17701 :  615
18015 :  590
18901 :  610
18902 :  610
19111 :  615
19380 :  620
19609 :  610
20020 :  610
20640 :  615
20707 :  610
21045 :  610
21222 :  615
22003 :  615
22204 :  610
24801 :  50
25404 :  610
26003 :  610
2601 :  610
26034 :  620
26062 :  1310
26302 :  610
26505 :  1220
27106 :  605
28307 :  620
28345 :  610
28428 :  615
29577 :  610
29625 :  610
30046 :  615
30733 :  620
3253 :  615
33406 :  610
33467 :  615
33704 :  610
33914 :  610
34222 :  615
34234 :  610
34690 :  615
34972 :  610
36610 :  610
39532 :  610
40504 :  610
43206 :  610
43228 :  610
43920 :  615
43952 :  610
43953 :  620
43964 :  1220
44035 :  615
44281 :  610
44444 :  615
44510 :  620
44512 :  605
44705 :  610
44870 :  610
45429 :  610
45503 :  615
48221 :  610
48328 :  605
55347 :  605
56345 :  620
57108 :  610
61539 :  610
64836 :  610
6883 :  615
74053 :  605
75631 :  610
80246 :  610
85021 :  435
85024 :  610
85379 :  610
86406 :  610
87124 :  610
91352 :  605
92405 :  610

### Fatality rates: year-to-year comparison

In [32]:
def calc_percent_change():
    """loops through data dictionary to sum up fatalities by year, calculate % change from one year to the next, 
    and then print the output"""
    od_summary = sort_data_dict()
    prevkey = 0
    for i in sorted(od_summary['year']):
        print(i, ':',od_summary['year'][i], sep=' ', end='')
        # percent change = previous - current / previous
        if prevkey!= 0:
            percent_change = (od_summary['year'][i] - od_summary['year'][prevkey]) / od_summary['year'][prevkey]
            print(', change: ', percent_change)
            # move our cursor to remember the last key
        prevkey = i

calc_percent_change()

2007 : 273532008 : 28276, change:  0.03374401345373451
2009 : 26793, change:  -0.0524473051350969
2010 : 27451, change:  0.02455865337961408
2011 : 31689, change:  0.15438417543987468
2012 : 34969, change:  0.10350594843636593
2013 : 32875, change:  -0.05988160942549115
2014 : 37419, change:  0.13822053231939163
2015 : 51581, change:  0.3784708303268393
2016 : 78983, change:  0.5312421240379209
2017 : 90271, change:  0.14291683020396795
2018 : 52623, change:  -0.41705531122952
2019 : 60355, change:  0.14693194990783498
2020 : 49986, change:  -0.1718001822549913
2021 : 25, change:  -0.999499859960789

Since 2007, Allegheny County saw the highest number of fatal accidental drug overdoses in 2017 (90,271). 

The largest % change happened from 2015 to 2016, when total overdose fatalities in Allegheny County increased by 53%. 

Notably, there was a steep decline in fatalities (-41%) just two years later, from 2017 to 2018. 

The dataset is currently reporting a 17% decline in fatalities in 2020, but this seems like it could be subject to change. Since we are not even two months past the end of 2020, there may be additional 2020 data added to this dataset in the coming weeks (the low number of fatalities recorded in 2021 so far suggests that much of the data is entered on a delay). 

For further research, it would be interesting to break down the time-of-death data column by month to compare monthly changes in fatality rates.